apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherforecast-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherforecast-webapi
  template:
    metadata:
      labels:
        app: weatherforecast-webapi
    spec:
      containers:
        - name: weatherforecast-webapi
          image: personalproject.azurecr.io/weatherforecast-webapi:latest
          ports:
            - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: weatherforecast-webapi-service
spec:
  type: LoadBalancer
  selector:
    app: weatherforecast-webapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
